### ISSUE TITLE
how to install on linux (debian)?

### ISSUE THREAD

**Issue by marioseixas** [yohasebe/monadic-chat#4]
i've saw the instructions for MAC and Windows, but how about linux?

**Comment by yohasebe** [comment]
Currently, Linux packages aren't directly available because I don't have a Linux GUI desktop testing setup. The GUI console of Monadic Chat, which makes managing the docker container and starting/stopping the app easier, might need adjustments for Linux environments.

However, if you're comfortable with command-line operations, setting up the app on Linux and accessing it via a web browser should be quite straightforward.

I'll create Linux installation instructions sometime soon and will update this thread as soon as they're ready. Thanks for your patience and interest!
